// This file holds shared types for the Workbench module
export type ViewType =
  | 'workbench'
  | 'assets'
  | 'product_images_clothing_swap'
  | 'product_images_first_frame'
  | 'product_images_smart_repair'
  | 'product_images_gallery'
  | 'product_images_text_separation'
  | 'product_images_ai_model'
  | 'creative_lab_replay'
  | 'creative_lab_script_extract'
  | 'creative_lab_canvas'
  | 'community'
  | 'templates'
  | 'history'
  | 'agent'
  | 'editor'
  | 'profile'
  | 'billing'
  | 'ai_creator';
